### ISSUE TITLE
System.ArgumentException : Key [324F817A-7420-4E6D-B3C1-143FBED6D855] was not found when using CodeCoverage.runsettings file

### ISSUE THREAD

**Issue by 0x10-z** [javitolin/TemplateFormattedConfiguration#1]
Hello,

First, I find this nuget very useful. I don't really understand why dotnet is not including the same functionality by default.

Then, I noticed when you create integration tests in a dotnet application, and you use a custom CodeCoverage.runsettings file, integration tests fail due to a following error:

```c#
 Message: 
System.ArgumentException : Key [324F817A-7420-4E6D-B3C1-143FBED6D855] was not found

  Stack Trace: 
TemplateFormattedConfigurationProvider.ParseTemplatedConfiguration(IConfigurationSection child)
TemplateFormattedConfigurationProvider.Load()
TemplateFormattedConfiguration.Run()
TemplateFormattedConfigurationExtensions.EnableTemplatedConfiguration(IConfiguration configuration, TemplateFormattedConfigurationSettings settings)
Program.<Main>$(String[] args) line 6
--- End of stack trace from previous location ---
HostingListener.CreateHost()
<>c__DisplayClass10_0.<ResolveHostFactory>b__0(String[] args)
DeferredHostBuilder.Build()
WebApplicationFactory`1.CreateHost(IHostBuilder builder)
WebApplicationFactory`1.ConfigureHostBuilder(IHostBuilder hostBuilder)
WebApplicationFactory`1.EnsureServer()
WebApplicationFactory`1.CreateDefaultClient(DelegatingHandler[] handlers)
WebApplicationFactory`1.CreateDefaultClient(Uri baseAddress, DelegatingHandler[] handlers)
WebApplicationFactory`1.CreateClient(WebApplicationFactoryClientOptions options)
WebApplicationFactory`1.CreateClient()
BaseTestControllerShould.ctor(CustomWebApplicationFactory`1 factory) line 25
WhoamiShould.ctor(CustomWebApplicationFactory`1 factory) line 20
```

I've created a project from scratch to replicate this issue in my github: https://github.com/0x10-z/IntegrationTestsDotnet
There, last commit has what is needed to provoke this issue. Commit before (2nd one), without using following DataCollector, works fine (https://github.com/0x10-z/IntegrationTestsDotnet/commit/097b9051b1ae9996a232a6c4b834583fabb243f3):
```c#
<DataCollector friendlyName="Code Coverage" uri="datacollector://Microsoft/CodeCoverage/2.0" assemblyQualifiedName="Microsoft.VisualStudio.Coverage.DynamicCoverageDataCollector, Microsoft.VisualStudio.TraceCollector, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a">

</DataCollector>
```

Let me know if you need more information about it.

Thank you in advance,

Iker Ocio.

**Comment by javitolin** [comment]
Hi!
First of all I'm glad you like the nuget :-)

If I run your tests on debug, they pass without a problem.
The error you are seeing is because, for some reason, the code thinks "324F817A-7420-4E6D-B3C1-143FBED6D855" should be a key it should replace.
You can try setting `TemplatedConfigurationSettings.ThrowIfNotFound` to `false` and then I won't throw an exception. 
Tell me if this helps!

**Comment by 0x10-z** [comment]
Sorry for late response.
That setting worked like a charm, it is enough ;)

Thank you!

**Comment by javitolin** [comment]
Great to hear that!
